### ISSUE TITLE
MongoError ao tentar sacar para sua própria account

### ISSUE THREAD

**Issue by GCastilho** [GCastilho/unip-tcc#46]
O database do módulo externo dá um bug ao tentar executar um saque para sua própria account: `E11000 duplicate key error collection: exchange-<currency>.transactions`

Isso deve ser resolvido. Eu acho que a maneira mais simples é simplesmente impedir um saque para o mesmo endereço, mas dá pra aproveitar isso e resolver a questão de saque para uma account que pertence a nós

O que vc acha @gabr1gus ?

**Comment by GCastilho** [comment]
Na verdade, como esse erro é causado por um mesmo txid de um envio e recebimento, ele vai ocorrer toda vez que um usuário tentar mandar $$ para uma account que nos pertence, não só para ele mesmo

Uma solução simples seria transações de envio e recebimento ficarem em collections diferentes

A outra seria impedir isso, mas precisaria ter um check pra saber se o address é nosso a cada tentativa de envio, e isso parece bem pesado de se fazer

**Comment by gabr1gus** [comment]
> Uma solução simples seria transações de envio e recebimento ficarem em collections diferentes

isso é uma boa soluçao, pois embora eu consiga pensar em outras maneiras de resolver esse problema,(nao muito boas por sinal), a soluçao de separar as transaçoes de envio e recebimento em collections diferentes cria um padrao que evita problemas futuros em outras currencies que possam ser implementadas no sistema, alem disso, é basicamente a coisa mais facil para se fazer

uma outra soluçao nesse sentido é: adicionar um campo dizendo o tipo de transaçao: send ou receive, mas nao tem pra que isso

> A outra seria impedir isso, mas precisaria ter um check pra saber se o address é nosso a cada tentativa de envio, e isso parece bem pesado de se fazer

isso é um curativo, nao uma soluçao é menos do que ideal fazer algo do genero
