### ISSUE TITLE
Uma transação de saque menor que o fee faz o amount ser negativo

### ISSUE THREAD

**Issue by GCastilho** [GCastilho/unip-tcc#57]
Ao executar uma transação de saque em que o amount seja menor que o fee da operação o amount da transação fica negativo

Além de isso dar erro no saque, deixando a transação "travada" nos módulos externos (tbm acontece com a #54 ) isso tem potencial de causar algum efeito bizarro pelo resto do código

@gabr1gus e @joaojvds Eu acho que impedir uma tx com amount negativo de ser salvo uma boa por resolver bugs potenciais em definitivo, só q tem outro problema: um saque com o valor exato do fee vai fazer uma tx com valor de 0 de ser executada, q tbm dar problema. Um valor mínimo de transação seria uma possível solução

Então teria q fazer duas coisas: Impedir um amount negativo de ser salvo (que teria q fazer um verificador personalizado pq ele é um decimal128) e estabelecer um valor mínimo para um saque, tipo 2x o fee

Sugestões? Opiniões?

**Comment by gabr1gus** [comment]
do ponto de vista do external modules da pra fazer uma verificação relacionada ao valor que vai ser enviado (se é maior que 0 por exemplo) e fazer handlers para erros na funçao de send relacionados ao assunto. 
É, provavelmente, desnecessario fazer algo do genero, pois erros do tipo não deveriam nem passar do main server, na verdade não deveriam passar nem do client

**Comment by gabr1gus** [comment]
> e estabelecer um valor mínimo para um saque, tipo 2x o fee

uma outra maneira seria um fee porcentual para valores depois de certas quantias (um fee que desincentivasse o saque de pequenas quantias, mas que as permitissem mesmo assim)
no entanto essa solução provavelmente seria complicada de implementar e os benefícios, ao meu ver, não valeriam a pena.
tendo em vista que estamos fazendo um trabalho universitário, recomendo uma implementação de "valor minimo para saque" client-side e que essa issue não seja fechada apos isso ser "resolvido" para servir como lembrete implementar alguma solução mais complicada e "correta"

**Comment by GCastilho** [comment]
>É, provavelmente, desnecessario fazer algo do genero, pois erros do tipo não deveriam nem passar do main server, na verdade não deveriam passar nem do client

Mas o problema é que, se isso acontece o sistema vai ficar com essa transação travada. O loop de envio vai parar nela toda vez e nunca vai ter uma maneira de sair dele

E esse check é simples, melhor implementar ele sim

>recomendo uma implementação de "valor minimo para saque" client-side e que essa issue não seja fechada apos isso ser "resolvido"

Nem precisa ser client-side. Faz a verificação server-side e coloca no cliente uma indicação de valor mínimo. Eu vi nas exchanges e todas elas tem valor mínimo de saque

**Comment by GCastilho** [comment]
Eu depois abro um PR para

- [x] Colocar uma indicação no cliente de um valor mínimo de saque

- [x] Impedir que saques menores que o 2x o fee sejam executadas

- [x] Adicionar uma verificação custom no db pra impedir que um amount negativo seja salvo (essa pode impedir vários bugs)

- [x] Adicionar um check nos external modules para não aceitarem transações com amount negativo

**Comment by GCastilho** [comment]
Uma nota: Não tem testes nos módulos externo, então não dá pra saber se o validador de amount está funcionando lá, mas provavelmente está
